files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 693390060FCB422D40D27A953DE5B4DC
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 693390060FCB422D40D27A953DE5B4DC
- generatedChecksum: F531755BD1294662F6F73405C0A22618
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F531755BD1294662F6F73405C0A22618
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D63C213DDCAABDC9F0488038A2B49517
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd1.c
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: SOURCE
  userChecksum: D63C213DDCAABDC9F0488038A2B49517
- generatedChecksum: 34E1F1AE3B58D234D5B720A5E9BF072A
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 34E1F1AE3B58D234D5B720A5E9BF072A
- generatedChecksum: 293C3FE1970F234F6DC8EED22935AB7C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 293C3FE1970F234F6DC8EED22935AB7C
- generatedChecksum: 30C451ABD0949EAADD6E2BC3F99C6A82
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 30C451ABD0949EAADD6E2BC3F99C6A82
- generatedChecksum: 6487682FFAA9209E23EE5326D5B63E45
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6487682FFAA9209E23EE5326D5B63E45
- generatedChecksum: F266610F25A6EEA29FB0A3E551A87CD0
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi2_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: F266610F25A6EEA29FB0A3E551A87CD0
- generatedChecksum: 0BC42098D946D1FD451DEBE7616F3654
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0BC42098D946D1FD451DEBE7616F3654
- generatedChecksum: DC21C3E6D6DCE78BF5C476F8902F3DC5
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC21C3E6D6DCE78BF5C476F8902F3DC5
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: E375121C76D3B37766CBE019F2328B76
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E375121C76D3B37766CBE019F2328B76
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd1.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
- generatedChecksum: AEFE39C8E52415FE642815364C699E0C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd_common.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AEFE39C8E52415FE642815364C699E0C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: AC36F429D7162D7D1A68B9955ED194A3
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: AC36F429D7162D7D1A68B9955ED194A3
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: 46BEF984B2C3CCCFEBA8160E19DA9AAA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 46BEF984B2C3CCCFEBA8160E19DA9AAA
- generatedChecksum: 86579BD2296BD0B25C7B6BD7167E9087
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi2_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 86579BD2296BD0B25C7B6BD7167E9087
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 38A7F5DCE6FE0F7B9E02AA5446AC3B68
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 38A7F5DCE6FE0F7B9E02AA5446AC3B68
- generatedChecksum: 3D9C5CE392D10EAD2D420FED1445597A
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D9C5CE392D10EAD2D420FED1445597A
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 7FABE4A9D0883C99ADAA9CA9BB4362C5
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 7FABE4A9D0883C99ADAA9CA9BB4362C5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
