format_version: v1.0
type: UniqueComponent
attributes: {id: uart2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '460800'}
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '43'}
  - type: Comment
    attributes: {id: UART_BAUD_PER_ERROR_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Baud Error = -1.0493 % ***'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '0'}
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: UART_CLKSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '80250000'}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '131080'}
- type: ElementPosition
  attributes: {x: '620', y: '20', id: uart2}
