files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/can-fd
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: E4D4C472050D034A3878760BCF434F60
  logicalPath: config/can-fd
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4D4C472050D034A3878760BCF434F60
- generatedChecksum: DEDDDA0359CC0398A6192F794A86A9F3
  logicalPath: config/can-fd
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DEDDDA0359CC0398A6192F794A86A9F3
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: 3213CA481ED737A308839C3ED86ADA8C
  logicalPath: config/can-fd/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3213CA481ED737A308839C3ED86ADA8C
- generatedChecksum: 3649EEABDEE9E0240E2655B20C8C00FB
  logicalPath: config/can-fd/peripheral/canfd
  name: plib_canfd1.c
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3649EEABDEE9E0240E2655B20C8C00FB
- generatedChecksum: E10E5B66CAADECE1C00BACB3A8008D6E
  logicalPath: config/can-fd/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E10E5B66CAADECE1C00BACB3A8008D6E
- generatedChecksum: CDE489012C46160ED6A67092B2FFCE99
  logicalPath: config/can-fd/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE489012C46160ED6A67092B2FFCE99
- generatedChecksum: 6F6B471B0C0181422878659A23CB9BAA
  logicalPath: config/can-fd/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F6B471B0C0181422878659A23CB9BAA
- generatedChecksum: 212C8AC9CF64082BDF23CAE7705BD0AF
  logicalPath: config/can-fd/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 212C8AC9CF64082BDF23CAE7705BD0AF
- generatedChecksum: E7A08784221B98A7462809A4C33ED738
  logicalPath: config/can-fd/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: E7A08784221B98A7462809A4C33ED738
- generatedChecksum: 9CCF87C604FB3759C0048FF2B0C07748
  logicalPath: config/can-fd/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9CCF87C604FB3759C0048FF2B0C07748
- generatedChecksum: BD9CB061968B38179ABBF9B53E47A080
  logicalPath: config/can-fd/peripheral/rtcc
  name: plib_rtcc.c
  physicalPath: peripheral/rtcc
  security: NON_SECURE
  type: SOURCE
  userChecksum: BD9CB061968B38179ABBF9B53E47A080
- generatedChecksum: 3DBD5C08EB7DB8D666609DC772B98418
  logicalPath: config/can-fd/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3DBD5C08EB7DB8D666609DC772B98418
- generatedChecksum: A81E20875613CD9E47E4F7AD47132195
  logicalPath: config/can-fd/peripheral/spi/spi_master
  name: plib_spi2_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: A81E20875613CD9E47E4F7AD47132195
- generatedChecksum: A182F1654C0D24C85A99FB6772C9FC2F
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr5.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: A182F1654C0D24C85A99FB6772C9FC2F
- generatedChecksum: 664AA2121585BF2FC6604AA4D0FB6EC0
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr6.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 664AA2121585BF2FC6604AA4D0FB6EC0
- generatedChecksum: 032D470A04F8D851EE214F74E7177E82
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr9.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 032D470A04F8D851EE214F74E7177E82
- generatedChecksum: CAD1D811DE4EFDDB360498A387645C51
  logicalPath: config/can-fd/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: CAD1D811DE4EFDDB360498A387645C51
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/can-fd/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: F11A609368E92836A4C9BA6044599384
  logicalPath: config/can-fd
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F11A609368E92836A4C9BA6044599384
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/can-fd
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/can-fd
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: B2EE65C30069B4D8072900E7D5C17151
  logicalPath: config/can-fd/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: B2EE65C30069B4D8072900E7D5C17151
- generatedChecksum: A53A85C7B14CA7105C1164E0FC3C5973
  logicalPath: config/can-fd/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: A53A85C7B14CA7105C1164E0FC3C5973
- generatedChecksum: D761D4F0FE91A7E4A56806CF00C6BC16
  logicalPath: config/can-fd/peripheral/canfd
  name: plib_canfd1.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: D761D4F0FE91A7E4A56806CF00C6BC16
- generatedChecksum: AEFE39C8E52415FE642815364C699E0C
  logicalPath: config/can-fd/peripheral/canfd
  name: plib_canfd_common.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AEFE39C8E52415FE642815364C699E0C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/can-fd/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 07F6F97AE60963B2D2AE2345013D9FDC
  logicalPath: config/can-fd/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 07F6F97AE60963B2D2AE2345013D9FDC
- generatedChecksum: AC36F429D7162D7D1A68B9955ED194A3
  logicalPath: config/can-fd/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: AC36F429D7162D7D1A68B9955ED194A3
- generatedChecksum: 18185DBF071F6CF62BBD9539E97594AD
  logicalPath: config/can-fd/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 18185DBF071F6CF62BBD9539E97594AD
- generatedChecksum: C4C5F1A3785536F3AD5A50C28E5883B2
  logicalPath: config/can-fd/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: C4C5F1A3785536F3AD5A50C28E5883B2
- generatedChecksum: 27E3133B231E478BA73BA33157C30342
  logicalPath: config/can-fd/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 27E3133B231E478BA73BA33157C30342
- generatedChecksum: 475983F6F8CF7A0AF4A75B21D75A2179
  logicalPath: config/can-fd/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 475983F6F8CF7A0AF4A75B21D75A2179
- generatedChecksum: C5CCB53DBC284D1BCEAB7756ED870B04
  logicalPath: config/can-fd/peripheral/rtcc
  name: plib_rtcc.h
  physicalPath: peripheral/rtcc
  security: NON_SECURE
  type: HEADER
  userChecksum: C5CCB53DBC284D1BCEAB7756ED870B04
- generatedChecksum: A9C21E81CB403E638EEB811A7780088B
  logicalPath: config/can-fd/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C21E81CB403E638EEB811A7780088B
- generatedChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
  logicalPath: config/can-fd/peripheral/spi/spi_master
  name: plib_spi2_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: DD36DE6ACD8AE29EFBB17C8C6B4E962E
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/can-fd/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: F2EC16614F2AB337E1005D068DF004A9
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr5.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: F2EC16614F2AB337E1005D068DF004A9
- generatedChecksum: CADC791B8E45B0CBF877D2802F32B46B
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr6.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: CADC791B8E45B0CBF877D2802F32B46B
- generatedChecksum: D58F20DA56BE2E621A2F826E3F201DB0
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr9.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D58F20DA56BE2E621A2F826E3F201DB0
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/can-fd/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 442A504503193FF627F7C0952797B7BD
  logicalPath: config/can-fd/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 442A504503193FF627F7C0952797B7BD
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/can-fd/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/can-fd
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: AD9028722C1D5DA19709387A0D18B3A5
  logicalPath: config/can-fd
  name: p32MK0512MCJ048.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: AD9028722C1D5DA19709387A0D18B3A5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/can-fd;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/can-fd;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
